# Generated by Django 5.2.7 on 2025-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('Teacher', 'TEACHER')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
