# Generated by Django 5.2.7 on 2025-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
