# Generated by Django 5.2.7 on 2025-10-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(to='blog.reply'),
        ),
    ]
