# Generated by Django 5.2.7 on 2025-10-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_reply_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
